#!/bin/bash
# Collect platform and GPU specs from the running board as JSON. The paper
# build (docs/paper/build.py) renders its two spec tables from this file,
# so the tables are generated by the system rather than transcribed.
#
#   bash collect_specs.sh > specs.json
set -u

vk() { vulkaninfo 2>/dev/null; }
VKDUMP=$(vk)
lim() { echo "$VKDUMP" | grep -m1 "$1" | grep -o '[0-9]\+' | head -1; }

MODEL=$(tr -d '\0' < /proc/device-tree/model)
SOC=$(grep -m1 -o 'BCM[0-9]*' /proc/device-tree/compatible 2>/dev/null | head -1)
[ -z "$SOC" ] && SOC=$(tr -d '\0' < /proc/device-tree/compatible | grep -o 'bcm[0-9]*' | head -1 | tr a-z A-Z)
CPU=$(lscpu | awk -F: '/Model name/{gsub(/^ */,"",$2); print $2; exit}')
NCPU=$(nproc)
ARM_HZ=$(vcgencmd measure_clock arm | cut -d= -f2)
V3D_HZ=$(vcgencmd measure_clock v3d | cut -d= -f2)
RAM_KB=$(awk '/MemTotal/{print $2}' /proc/meminfo)
OS=$(. /etc/os-release && echo "$PRETTY_NAME")
DIETPI=$(awk -F= '/CORE|SUB|RC/{v=v $2 "."} END{sub(/\.$/,"",v); print v}' /boot/dietpi/.version 2>/dev/null)
KERNEL=$(uname -r)
FW=$(vcgencmd version | head -1 | awk '{print $1}')

GPU_NAME=$(echo "$VKDUMP" | grep -m1 'deviceName' | sed 's/.*= //')
DRIVER=$(echo "$VKDUMP" | grep -m1 'driverInfo' | sed 's/.*= //')
API=$(echo "$VKDUMP" | grep -m1 'apiVersion' | grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+' | head -1)

cat <<EOF
{
  "collected_utc": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "platform": {
    "model": "$MODEL",
    "soc": "$SOC",
    "cpu": "$NCPU x $CPU",
    "cpu_clock_mhz": $((ARM_HZ / 1000000)),
    "ram_gb": $((RAM_KB / 1024 / 1024 + 1)),
    "os": "$OS (DietPi $DIETPI)",
    "kernel": "$KERNEL",
    "firmware": "$FW"
  },
  "gpu": {
    "device": "$GPU_NAME",
    "driver": "$DRIVER",
    "vulkan_api": "$API",
    "core_clock_mhz": $((V3D_HZ / 1000000)),
    "max_workgroup_invocations": $(lim maxComputeWorkGroupInvocations),
    "max_shared_memory_bytes": $(lim maxComputeSharedMemorySize),
    "subgroup_size": $(lim '^	subgroupSize'),
    "shader_float16": $(echo "$VKDUMP" | grep -m1 'shaderFloat16' | grep -q true && echo true || echo false),
    "cooperative_matrix": $(echo "$VKDUMP" | grep -qi 'cooperative_matrix' && echo true || echo false)
  }
}
EOF
